### ISSUE TITLE
Does ember engines still require canary?

### ISSUE THREAD

**Issue by christophermlne** [dgeb/ember-engines#120]

**Comment by dgeb** [comment]
ember-engines 0.2.x should be compatible with ember 2.6 betas (and 2.6 final, to be released next week). Even as master progresses, we will maintain a 2.6-compatible branch that we can patch as needed, so that future 0.2.x releases can be published with bug fixes.

We've been pushing a lot of the overrides in ember-engines upstream to ember core in an effort to stabilize the addon to use only public interfaces in ember. This work has been mirrored by work in a `clean` branch in ember-engines, which trims out the code pushed upstream. Once `clean` has been merged to `master`, I'll update this addon's readme with more notes about compatibility.

**Comment by runspired** [comment]
I can confirm I'm using this successfully against 2.6 beta.

**Comment by dgeb** [comment]
The `clean` branch has now been merged into `master`, so you have a choice of using `master` along with Ember canary or the `v0.2` branch along with Ember 2.6.x. I've added [some notes to the README](https://github.com/dgeb/ember-engines#important-note-about-compatibility-and-stability).
