### ISSUE TITLE
'.' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by RayKwon** [dgeb/ember-engines#182]
Hello team,

I just got an error message during `npm install` after cloning the repository.
The error message is as follow :

> '.' is not recognized as an internal or external command, operable program or batch file.

I did `npm install` from Windows machine, haven't tried yet in other OS.
Any idea?

![image](https://cloud.githubusercontent.com/assets/891212/17608625/059ad076-6071-11e6-8023-8d2ba47a7d4c.png)

**Comment by nathanhammond** [comment]
@RayKwon Can you attempt to run the script directly? `./bin/install-test-addons.sh`

It appears to be breaking because of that invocation pattern. It's an executable shell script and I don't know how that works inside of MinGW. None of the rest of us are on Windows so you're on your own to work through this. Please post updates with what you figure out.

**Comment by RayKwon** [comment]
Sorry for late comment, I executed `.bin/install-test-addons.sh` and ran successfully. Thanks @nathanhammond .

**Comment by nathanhammond** [comment]
Thanks @RayKwon for the update. 👍 Closing.
