### ISSUE TITLE
Don’t run asset manifest generator when there are no lazy engines?

### ISSUE THREAD

**Issue by sheldonnbbaker** [dgeb/ember-engines#206]
Advised as per @nathanhammond.

I was using master in an attempt to extract out some common logic in my parent application into an in-repo engine, followed the guide in the README, and got stuck on the error: `Asset manifest does not list any available bundles` in `asset-loader#loadBundle`.

**Comment by nathanhammond** [comment]
Unsure if this is exactly the issue, but seems like something we should figure out.

**Comment by trentmwillis** [comment]
Mentioned this briefly in slack, but this error actually seems to be happening because we hit [this code path for lazy engines](https://github.com/dgeb/ember-engines/blob/master/addon/-private/router-ext.js#L167-L168) even when the Engine isn't being lazy. Will need a reproduction in order to investigate further.

That said, we likely should run any of the asset-manifest stuff as an optimization if it is just going to be empty anyway.

**Comment by trentmwillis** [comment]
Just ran into this with our application, so I'll dive into it.

**Comment by trentmwillis** [comment]
So after looking into it, turns out the issue was not having the right version of `ember-resolver` 😆 . Just make sure you have version `^2.1.0`.

Anyway, do we want to keep this issue open to address optimizing the asset manifest generator work?

**Comment by nathanhammond** [comment]
I think we should open a different issue for that. They're free.
