### ISSUE TITLE
Questions about workflow

### ISSUE THREAD

**Issue by nucleartide** [dgeb/ember-engines#67]
Hey all, I just had some questions about how to develop engines:

1. Within an in-repo addon/engine, would I be able to use ember-cli to generate framework entities (like components, templates, etc.)? Or do I have to create new files manually?
2. How do you test the framework entities in an in-repo addon? I've noticed in other addons that people generally import things into their main `app/` directory, so would the tests just exist in the base application and thus outside of the addon/engine?

Thanks!

**Comment by trentmwillis** [comment]
1. Should work, since it is possible to generate in-repo-addon versions of things by using the `--in-repo-addon=<addon-name>` flag. So to generate a component in an in-repo-addon named `my-engine` you would do `ember g component foo-bar --in-repo-addon=my-engine`

2. Currently there is no real test support for in-repo-addons that I am aware of (here's [an old issue for it](https://github.com/ember-cli/ember-cli/issues/4461)), so yeah you'll probably have to test things within the consuming application or use a standalone addon/engine.

**Comment by dgeb** [comment]
Thanks for replying @trentmwillis. I agree completely.

@nucleartide please file addon specific issues with the ember-cli project and let us know if you have any other questions related to engines.
